Dev/nav
leggedrobotics/se2_navigation pull request #21
Opened 2023-03-07 18:06 UTC by Idate96

Introduces new functionality to:
- do velocity control 
- use the nav msg as target goal 
- possible inconstistency if breking distance does not match with nominal vel and acc
- more robust update for the segment id for the path tracker 
- 2 points paths removed

2023-03-28 14:03 UTC, nubertj requested changes
why is config and param needed both?

Good to merge after replying and renaming the var imo

2023-03-28 14:03 UTC, nubertj commented on pure_pursuit_core/include/pure_pursuit_core/heading_control/HeadingController.hpp
> +  double maxPathDistance_ = 1.0;
maxPathDeviation_ would be better, similar to your comment

2023-03-28 14:03 UTC, nubertj commented on pure_pursuit_core/src/SimplePathTracker.cpp
> +  // remove from path segments that have less than two points (they are not valid for pure pursuit)
this is only ran once in the beginning after importing the path, right?
Otherwise it could maybe be implementted more efficiently...

2023-03-28 14:03 UTC, nubertj commented on pure_pursuit_core/src/SimplePathTracker.cpp
> +  // remove from path segments that have less than two points (they are not valid for pure pursuit)
what happened before with the pure pursuit with these segments?

2023-03-28 14:03 UTC, nubertj commented on pure_pursuit_ros/src/AckermannSteeringControllerRos.cpp
> +  param->maxPathDistance_ = config.max_path_distance;
rename

2023-03-28 14:03 UTC, nubertj commented on pure_pursuit_ros/config/PurePursuit.cfg
having some comments in the config would be nice I assume.

2023-03-28 14:03 UTC, nubertj commented on se2_navigation_msgs/srv/RequestPathSrvPresetGoal.srv
> +bool status
newline

2024-12-17 17:12 UTC, jelavice commented
Closing due to inactivity. Feel free to reopen

2024-12-17 17:12 UTC, closed without merging

2024-12-17 17:30 UTC, nubertj commented
yes, I will let @Idate96 decide whether he wants to further follow up on this or not